/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package absensi;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author YOGA SAPUTRA
 */
public class form1 extends javax.swing.JFrame {
    Connection con;
    Resultset rs;
    PreparedStatement pst;
    /**
     * Creates new form form1
     */
    String id_login = session.getId_login();
    String username = session.getUsername();
    
    
    public form1() {
        initComponents();
        setLocationRelativeTo(null);
        con=koneksi.koneksiDB();
        tampildata();
        waktu();
        
        jamtx.disable();
        tangltx.disable(); //untuk mengunci field 
        namafield.disable();//disable=dikunci
    }
     public void absen(){ 
        
        String nama =namafield.getText(); //untuk membaca inputan nama di awal login
       java.util.Date today = new java.util.Date(); //akses tanggal secara langsung
       java.sql.Timestamp waktu = new java.sql.Timestamp(today.getTime());// antara jam sama tanggal menjadi satu kolom= timestamp
        try { //
            String query = "insert into absensi (user,jam_masuk) value(?,?)";//memberikan inputan ke jam masuk
             pst = con.prepareStatement(query);
            pst.setString(1,nama);//menginputkan ke kolom user di dabes dengan inputan yang diambil dari nama field/yang dikunci/yg diloginkan
            pst.setTimestamp(2,waktu );//menginputkan ke kolom jam masuk dengan inputan yang diambil dari library timestamp
//            pst.setDate(3, (Date) today);
            pst.execute();// untuk mengaksikan semua priper statement/pst
        } catch (Exception e) { //pesan eror
            System.out.println(e);
        }
    }
      public void absenkeluar(){
        String jam = jTextField8.getText();
        String tanggal=tangltx.getText();
        String nama =namafield.getText();
       java.util.Date today = new java.util.Date();
       java.sql.Timestamp waktu = new java.sql.Timestamp(today.getTime());
        try {
            String query = "insert into absensi (user,jam_keluar) value(?,?)";// memberikan inputan ke jam keluar
             pst = con.prepareStatement(query);
            pst.setString(1,nama);
            pst.setTimestamp(2,waktu );
//            pst.setDate(3, (Date) today);
            pst.execute();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public void waktu() {
        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    Calendar cal = Calendar.getInstance();
                   SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
                    SimpleDateFormat format2 = new SimpleDateFormat("yyyy-MM-dd");
                    jamtx.setText(format.format(cal.getTime()));
                    tangltx.setText(format2.format(cal.getTime()));
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(form1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        clock.start();
    }
    public void tampildata(){
        String sql ="SELECT * FROM profile WHERE id_log=?";// select selalu pakai execute query krn tidak ada perubahan data 
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, id_login);
            ResultSet rs=pst.executeQuery();//tidak ada perubahan data
            while(rs.next()){ //mengunci sesion pada baris tabel 
                idtxt.setText(id_login);
                userntxt.setText(username);
                namafield.setText(rs.getString("nama"));//nampilin data dari dabes dengan kolom nama yang dieksekusi pada nama field 
//                txtnama.setText(rs.getString("nama"));
                txtalamat.setText(rs.getString("alamat"));//nampilin data dari dabes dengan kolom alamat yang dieksekusi pada txtalamat(Jlabel)
                txttelpon.setText(rs.getString("no_telphon"));
            }
        } catch (Exception e) {
        }
        absen();// memanggil kodingan pada/ di method void=absen 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idtxt = new javax.swing.JLabel();
        userntxt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txttelpon = new javax.swing.JLabel();
        txtalamat = new javax.swing.JLabel();
        jamtx = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tangltx = new javax.swing.JButton();
        namafield = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel1.setText("FORM DATA KARYAWAN");

        idtxt.setText("id");

        userntxt.setText("username");

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Nomer telpon");

        txttelpon.setText("jLabel5");

        txtalamat.setText("jLabel5");

        jamtx.setText("jam");

        jLabel5.setText("ID");

        jLabel6.setText("USERNAME");

        tangltx.setText("tanggal");
        tangltx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tangltxActionPerformed(evt);
            }
        });

        namafield.setText("jTextField1");

        jTextField8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField8.setEnabled(false);
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
        });
        jTextField8.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTextField8ComponentHidden(evt);
            }
        });
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttelpon, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userntxt)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idtxt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(namafield, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(jamtx)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(tangltx, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jamtx)
                            .addComponent(tangltx, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtxt)
                    .addComponent(jLabel5)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userntxt)
                    .addComponent(jLabel6))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtalamat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttelpon))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        login lg = new login();//manggil kelas login 
        lg.setVisible(true);//menampilkan kelas login
        dispose();// menutup kelas form 1
        absenkeluar();//memanggil kodingan pada absenkeluar / otomatis mengisi kolom jam keluar
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tangltxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tangltxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tangltxActionPerformed

    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8MouseClicked

    private void jTextField8ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextField8ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ComponentHidden

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton jamtx;
    private javax.swing.JTextField namafield;
    private javax.swing.JButton tangltx;
    private javax.swing.JLabel txtalamat;
    private javax.swing.JLabel txttelpon;
    private javax.swing.JLabel userntxt;
    // End of variables declaration//GEN-END:variables
}
